/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Icon: typeof import('@iconify/vue')['Icon']
    MyBreadcrumb: typeof import('./components/MyBreadcrumb.vue')['default']
    MyButton: typeof import('./components/MyButton.vue')['default']
    MyDialog: typeof import('./components/MyDialog.vue')['default']
    MyErrorMessage: typeof import('./components/MyErrorMessage.vue')['default']
    MyImage: typeof import('./components/MyImage.vue')['default']
    MyInputFile: typeof import('./components/MyInputFile.vue')['default']
    MyLoading: typeof import('./components/MyLoading.vue')['default']
    MyModal: typeof import('./components/MyModal.vue')['default']
    MyPulseLoading: typeof import('./components/MyPulseLoading.vue')['default']
    MyToast: typeof import('./components/MyToast.vue')['default']
    OnClickOutside: typeof import('@vueuse/components')['OnClickOutside']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VxeGrid: typeof import('vxe-table')['VxeGrid']
    VxePager: typeof import('vxe-table')['VxePager']
  }
}
