#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER bs_dev WITH CREATEDB ENCRYPTED PASSWORD 'bs_dev';
  CREATE DATABASE bs_dev OWNER bs_dev TEMPLATE template0 ENCODING 'UTF8' LC_COLLATE 'ja_JP.utf8' LC_CTYPE 'ja_JP.utf8';
  GRANT ALL PRIVILEGES ON DATABASE bs_dev TO bs_dev;

  CREATE USER bs_ut WITH ENCRYPTED PASSWORD 'bs_ut';
  CREATE DATABASE bs_ut OWNER bs_ut TEMPLATE template0 ENCODING 'UTF8' LC_COLLATE 'ja_JP.utf8' LC_CTYPE 'ja_JP.utf8';
  GRANT ALL PRIVILEGES ON DATABASE bs_ut TO bs_ut;
EOSQL
