/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    InputPassword: typeof import('./component/InputPassword.vue')['default']
    MyBreadcrumb: typeof import('./component/MyBreadcrumb.vue')['default']
    MyButton: typeof import('./component/MyButton.vue')['default']
    MyLoading: typeof import('./component/MyLoading.vue')['default']
    MyPaginator: typeof import('./component/MyPaginator.vue')['default']
    OnClickOutside: typeof import('@vueuse/components')['OnClickOutside']
    QuillEditor: typeof import('./component/QuillEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
